name: Deploy to Firebase

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      # Build and deploy frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build frontend
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_ENV: PROD
        run: npm run build
        
      # Build and deploy functions
      - name: Install functions dependencies
        working-directory: ./functions
        run: npm ci
        
      - name: Build functions
        working-directory: ./functions
        run: npm run build
        
      # Deploy to Firebase Production
      - name: Deploy to Firebase Production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Set functions environment variables for production
          firebase functions:config:set gemini.api_key="${GEMINI_API_KEY}" --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
          
          # Deploy hosting and functions to production
          firebase deploy --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}