name: Deploy to Firebase Dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      # Build and deploy frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      # Build and deploy functions
      - name: Install functions dependencies
        working-directory: ./functions
        run: npm ci
        
      - name: Build functions
        working-directory: ./functions
        run: npm run build
        
      # Deploy to Firebase Dev Environment
      - name: Deploy to Firebase Dev Environment
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GEMINI_API_KEY_DEV: ${{ secrets.GEMINI_API_KEY_DEV }}
        run: |
          # Set functions environment variables for dev
          firebase functions:config:set gemini.api_key="${GEMINI_API_KEY_DEV}" --project insieme-dev-d7459 --token ${FIREBASE_TOKEN}
          
          # Deploy hosting and functions to dev
          firebase deploy --project insieme-dev-d7459 --token ${FIREBASE_TOKEN}